### ISSUE TITLE
PRACTICA PROPOSICIONES NESTOR CRUZ LEON

### ISSUE THREAD

**Issue by Nestor283** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Nestor283#1]
[MATEMATICAS_ DISCRETAS_PROPOSICIONES_NESTOR_CRUZ_LEON..pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Nestor283/files/13193663/MATEMATICAS_.DISCRETAS_PROPOSICIONES_NESTOR_CRUZ_LEON.pdf)

**Comment by Felix-Angel** [comment]
Portada: 25/25
Procedimiento: 25/25
Figuras e ilustraciones: 17/25 (Enlista solo 4 imágenes en su tabla de ilustraciones)
Conclusiones: 25/25
total: 92/100
Final: 18/20

Calificado por equipo de: Mayra, Diego, Felix, Alejandro

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
